-- load_predicted_phas.sql
-- Load Random Forest predictions for unlabelled objects into NEO Hazard Assessment Database
-- 
-- NOTE: This file should ONLY be run AFTER running the Random Forest inference pipeline.
-- If all objects in the database already have known PHA status (fully labelled set), 
-- this file will have no data to load (predictions_unlabelled.csv may be empty or not exist).
-- 
-- The predictions file is generated by:
--   python run_pipeline.py --input data/sbdb_query_results.csv --outdir .
-- 
-- This table is separate from the main NEO table because predicted PHA status
-- represents model inference on previously unlabelled objects, not ground truth.
-- The two-column structure (spkid, pred_pha) maintains a clean audit trail of
-- which objects have been classified by the ML model vs. official sources.

CREATE TABLE IF NOT EXISTS PredictedPHAs (
    spkid VARCHAR(50) PRIMARY KEY,
    pred_pha CHAR(1) NOT NULL CHECK (pred_pha IN ('Y', 'N')),
    prediction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Step 2: Clear existing predictions for fresh load (optional - comment out if UPSERT desired)
-- TRUNCATE TABLE PredictedPHAs;

-- Step 3: Load predictions from Random Forest inference output if not empty
LOAD DATA LOCAL INFILE './pha_classifier/predictions_unlabelled.csv'
INTO TABLE PredictedPHAs
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(spkid, @full_name, @class, @pha_prob, pred_pha)
SET prediction_date = CURRENT_TIMESTAMP;