DROP TABLE IF EXISTS CloseApproaches;
DROP TABLE IF EXISTS Observation;
DROP TABLE IF EXISTS OrbitalData;
DROP TABLE IF EXISTS PhysicalInfo;
DROP TABLE IF EXISTS Observatory;
DROP TABLE IF EXISTS NEOs;