SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS ObservationRecord;
DROP TABLE IF EXISTS CloseApproaches;
DROP TABLE IF EXISTS OrbitalData;
DROP TABLE IF EXISTS PhysicalInfo;
DROP TABLE IF EXISTS NEOs;

SET FOREIGN_KEY_CHECKS = 1;