-- load_anomalies.sql
-- Load anomaly flags for orbital parameters (MOID, e, inclination) into NEO Hazard Assessment Database
--
-- This table stores per-object anomaly flags for three orbital parameters:
--   - MOID (Minimum Orbit Intersection Distance)
--   - Eccentricity (e)
--   - Inclination (i)
--
-- Anomalies are determined by class-wise z-score exceeding threshold (|z| > 2.0)
-- 'Y' indicates the parameter value is anomalous for its orbital class
-- 'N' indicates normal/non-anomalous value
--
-- The combined anomaly_flag indicates if ANY parameter is anomalous for that object
--
-- Generated by: anomaly_flagger/flagger.py
-- load_anomalies.sql (UPSERT version - no data replacement)
-- Load anomaly flags without replacing existing data

-- Create the anomalies table (if it doesn't exist)
CREATE TABLE IF NOT EXISTS OrbitalAnomalies (
    spkid VARCHAR(50) PRIMARY KEY,
    class VARCHAR(20) NOT NULL,
    moid_anomaly CHAR(1) NOT NULL CHECK (moid_anomaly IN ('Y', 'N')),
    e_anomaly CHAR(1) NOT NULL CHECK (e_anomaly IN ('Y', 'N')),
    i_anomaly CHAR(1) NOT NULL CHECK (i_anomaly IN ('Y', 'N')),
    anomaly_flag CHAR(1) NOT NULL CHECK (anomaly_flag IN ('Y', 'N')),
    detection_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    -- Indexes for querying
    INDEX idx_class (class),
    INDEX idx_anomaly_flag (anomaly_flag),
    INDEX idx_moid_anomaly (moid_anomaly),
    INDEX idx_e_anomaly (e_anomaly),
    INDEX idx_i_anomaly (i_anomaly)
);

-- Create temporary staging table for the CSV data
CREATE TEMPORARY TABLE temp_anomalies (
    spkid VARCHAR(50),
    class VARCHAR(20),
    moid_anomaly CHAR(1),
    e_anomaly CHAR(1),
    i_anomaly CHAR(1),
    anomaly_flag CHAR(1)
);

-- Load CSV data into temporary table (doesn't affect main table yet)
LOAD DATA LOCAL INFILE './anomaly_flagger/anomalies_only.csv'
INTO TABLE temp_anomalies
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(spkid, class, moid_anomaly, e_anomaly, i_anomaly, anomaly_flag);

-- Update existing records (preserve history, just update anomaly status)
UPDATE OrbitalAnomalies o
JOIN temp_anomalies t ON o.spkid = t.spkid
SET 
    o.class = t.class,
    o.moid_anomaly = t.moid_anomaly,
    o.e_anomaly = t.e_anomaly,
    o.i_anomaly = t.i_anomaly,
    o.anomaly_flag = t.anomaly_flag,
    o.detection_date = CURRENT_TIMESTAMP;

-- Insert new records (only for spkids not already in the table)
INSERT INTO OrbitalAnomalies (spkid, class, moid_anomaly, e_anomaly, i_anomaly, anomaly_flag, detection_date)
SELECT 
    t.spkid, 
    t.class, 
    t.moid_anomaly, 
    t.e_anomaly, 
    t.i_anomaly, 
    t.anomaly_flag,
    CURRENT_TIMESTAMP
FROM temp_anomalies t
LEFT JOIN OrbitalAnomalies o ON t.spkid = o.spkid
WHERE o.spkid IS NULL;